"""Internal Codex console router definitions."""

from __future__ import annotations

from fastapi import APIRouter

from backend.services import codex_assistant, codex_console


def create_codex_console_router() -> APIRouter:
    router = APIRouter(tags=["codex-console"])
    router.add_api_route(
        "/api/admin/codex/status",
        codex_console.codex_status,
        methods=["GET"],
        name="codex_status",
    )
    router.add_api_route(
        "/api/admin/codex/tasks",
        codex_console.codex_listar_tarefas,
        methods=["GET"],
        name="codex_listar_tarefas",
    )
    router.add_api_route(
        "/api/admin/codex/tasks",
        codex_console.codex_criar_tarefa,
        methods=["POST"],
        name="codex_criar_tarefa",
    )
    router.add_api_route(
        "/api/admin/codex/attachments",
        codex_console.codex_upload_attachments,
        methods=["POST"],
        name="codex_upload_attachments",
    )
    router.add_api_route(
        "/api/admin/codex/tasks/{task_id}",
        codex_console.codex_obter_tarefa,
        methods=["GET"],
        name="codex_obter_tarefa",
    )
    router.add_api_route(
        "/api/admin/codex/tasks/{task_id}",
        codex_console.codex_deletar_tarefa,
        methods=["DELETE"],
        name="codex_deletar_tarefa",
    )
    router.add_api_route(
        "/api/admin/codex/conversations/{conversation_id}",
        codex_console.codex_deletar_conversa,
        methods=["DELETE"],
        name="codex_deletar_conversa",
    )
    router.add_api_route(
        "/api/admin/codex/tasks/{task_id}/approve",
        codex_console.codex_aprovar_tarefa,
        methods=["POST"],
        name="codex_aprovar_tarefa",
    )
    router.add_api_route(
        "/api/admin/codex/tasks/{task_id}/cancel",
        codex_console.codex_cancelar_tarefa,
        methods=["POST"],
        name="codex_cancelar_tarefa",
    )
    router.add_api_route(
        "/api/admin/codex/actions",
        codex_console.codex_actions_listar,
        methods=["GET"],
        name="codex_actions_listar",
    )
    router.add_api_route(
        "/api/admin/codex/functions",
        codex_console.codex_program_functions,
        methods=["GET"],
        name="codex_program_functions",
    )
    router.add_api_route(
        "/api/admin/codex/capabilities",
        codex_console.codex_capabilities_listar,
        methods=["GET"],
        name="codex_capabilities_listar",
    )
    router.add_api_route(
        "/api/admin/codex/capabilities/modules",
        codex_console.codex_capabilities_modules,
        methods=["GET"],
        name="codex_capabilities_modules",
    )
    router.add_api_route(
        "/api/admin/codex/capabilities/resolve",
        codex_console.codex_capabilities_resolver,
        methods=["POST"],
        name="codex_capabilities_resolver",
    )
    router.add_api_route(
        "/api/admin/codex/actions/proposals",
        codex_console.codex_actions_criar_proposta,
        methods=["POST"],
        name="codex_actions_criar_proposta",
    )
    router.add_api_route(
        "/api/admin/codex/actions/proposals/{proposal_id}/approve",
        codex_console.codex_actions_aprovar_proposta,
        methods=["POST"],
        name="codex_actions_aprovar_proposta",
    )
    router.add_api_route(
        "/api/admin/codex/actions/runs/{run_id}",
        codex_console.codex_actions_obter_execucao,
        methods=["GET"],
        name="codex_actions_obter_execucao",
    )
    router.add_api_route(
        "/api/admin/codex/actions/runs/{run_id}/cancel",
        codex_console.codex_actions_cancelar_execucao,
        methods=["POST"],
        name="codex_actions_cancelar_execucao",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/chat",
        codex_assistant.codex_assistant_chat,
        methods=["POST"],
        name="codex_assistant_chat",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/suggestions",
        codex_assistant.codex_assistant_suggestions,
        methods=["GET"],
        name="codex_assistant_suggestions",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/tools",
        codex_assistant.codex_assistant_tools,
        methods=["GET"],
        name="codex_assistant_tools",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/evaluation",
        codex_assistant.codex_assistant_evaluation_get,
        methods=["GET"],
        name="codex_assistant_evaluation_get",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/evaluation/run",
        codex_assistant.codex_assistant_evaluation_run,
        methods=["POST"],
        name="codex_assistant_evaluation_run",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/memory",
        codex_assistant.codex_assistant_memory_get,
        methods=["GET"],
        name="codex_assistant_memory_get",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/memory",
        codex_assistant.codex_assistant_memory_post,
        methods=["POST"],
        name="codex_assistant_memory_post",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/memory/{entry_id}",
        codex_assistant.codex_assistant_memory_delete,
        methods=["DELETE"],
        name="codex_assistant_memory_delete",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/data-sources",
        codex_assistant.codex_assistant_data_sources,
        methods=["GET"],
        name="codex_assistant_data_sources",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/bling/resources",
        codex_assistant.codex_assistant_bling_resources,
        methods=["GET"],
        name="codex_assistant_bling_resources",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/proactive/run",
        codex_assistant.codex_assistant_proactive_run,
        methods=["POST"],
        name="codex_assistant_proactive_run",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/daily-analysis/run",
        codex_assistant.codex_assistant_daily_analysis_run,
        methods=["POST"],
        name="codex_assistant_daily_analysis_run",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/reports",
        codex_assistant.codex_assistant_report_create,
        methods=["POST"],
        name="codex_assistant_report_create",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/reports/{report_id}",
        codex_assistant.codex_assistant_report_get,
        methods=["GET"],
        name="codex_assistant_report_get",
    )
    router.add_api_route(
        "/api/admin/codex/assistant/reports/{report_id}/download",
        codex_assistant.codex_assistant_report_download,
        methods=["GET"],
        name="codex_assistant_report_download",
    )
    return router
