"""Compatibility facade for the modular Context Hub domain."""

from backend.modules.context_hub.contracts import (
    CONTEXT_HUB_SCHEMA_VERSION,
    CONTEXT_RETRIEVAL_AUTHORITY_POLICY,
    CONTEXT_RETRIEVAL_FILTER_KEYS,
    CONTEXT_RETRIEVAL_V3,
    ContextHubConflictError,
    ContextHubError,
    ContextHubNotFoundError,
    ContextHubValidationError,
)
from backend.modules.context_hub.api import (
    bootstrap_context_hub,
    approve_curated_note,
    configure_context_hub,
    create_curated_backup,
    create_curated_note,
    get_generation,
    get_settings,
    get_status,
    list_generations,
    list_curated_backups,
    list_curated_notes,
    publish_curated_context,
    publish_generation,
    rebuild_context,
    rollback_generation,
    reject_curated_note,
    restore_curated_backup,
    review_curated_note,
    scan_context_hub_changes,
    scan_dlp,
    search_context,
    start_context_hub_watcher,
    stop_all_context_hub_watchers,
    stop_context_hub_watcher,
    update_settings,
    validate_curated_note,
)
from backend.modules.context_hub.contracts import ContextHubRuntimeConfig

__all__ = [
    "CONTEXT_HUB_SCHEMA_VERSION",
    "CONTEXT_RETRIEVAL_AUTHORITY_POLICY",
    "CONTEXT_RETRIEVAL_FILTER_KEYS",
    "CONTEXT_RETRIEVAL_V3",
    "ContextHubConflictError",
    "ContextHubError",
    "ContextHubNotFoundError",
    "ContextHubValidationError",
    "bootstrap_context_hub",
    "approve_curated_note",
    "configure_context_hub",
    "create_curated_backup",
    "create_curated_note",
    "get_generation",
    "get_settings",
    "get_status",
    "list_generations",
    "list_curated_backups",
    "list_curated_notes",
    "publish_curated_context",
    "publish_generation",
    "rebuild_context",
    "rollback_generation",
    "reject_curated_note",
    "restore_curated_backup",
    "review_curated_note",
    "scan_context_hub_changes",
    "scan_dlp",
    "search_context",
    "start_context_hub_watcher",
    "stop_all_context_hub_watchers",
    "stop_context_hub_watcher",
    "update_settings",
    "validate_curated_note",
]
