"""Compatibility facade for the modular sales-tool implementation."""

from __future__ import annotations

from backend.services.sales_tools import api
from backend.services.sales_tools.contracts import LEGACY_EXPORTS
from backend.services.sales_tools.runtime import SalesToolsRuntime
from backend.services.sales_tools import runtime


def configure_ia_tools_vendas_runtime(runtime_module=None, peers=None):
    return runtime.configure(runtime_module, peers)


_ia_stock_chart_number = api.stock_chart_number
_ia_stale_stock_chart_data = api.build_stale_stock_chart
_ia_stockout_chart_data = api.build_stockout_chart

_ia_tool_get_days_without_sale = api.get_days_without_sale
_ia_tool_get_days_without_sale_top = api.get_days_without_sale_top
_ia_tool_float = api.to_float
_ia_tool_resolver_sku = api.resolve_sku
_ia_tool_get_stock_data = api.get_stock_data
_ia_tool_get_sales_by_period = api.get_sales_by_period
_ia_tool_get_sales_quantity_by_period = api.get_sales_quantity_by_period
_ia_extrair_mes_ano_mensagem = api.extract_month_year
_ia_periodo_mensal_padrao = api.default_month_period
_ia_tool_get_sales_by_month_period = api.get_sales_by_month_period
_ia_tool_get_top_skus_sales_by_month = api.get_top_skus_sales_by_month
_ia_tool_get_top_skus_returns_by_month = api.get_top_skus_returns_by_month
_ia_tool_get_month_sales_returns_details = api.get_month_sales_returns_details
_ia_tool_get_sku_sales_by_month = api.get_sku_sales_by_month
_ia_extrair_meses_ano_mensagem = api.extract_months_year
_ia_tool_compare_sku_sales_months = api.compare_sku_sales_months
_ia_devolucoes_db_resumo = api.returns_summary
_ia_tool_get_returns_quantity_by_period = api.get_returns_quantity_by_period
_ia_tool_get_returns_by_period = api.get_returns_by_period
_ia_obter_data_referencia_vendas = api.get_sales_reference_date
_ia_tool_get_stockout_forecast = api.get_stockout_forecast
_ia_metricas_periodo_raw = api.period_metrics
_ia_tool_get_avg_ticket_by_period = api.get_avg_ticket_by_period
_ia_tool_get_return_rate_by_period = api.get_return_rate_by_period
_ia_tool_get_period_comparison = api.get_period_comparison
_ia_vendas_timeseries_raw = api.sales_timeseries_rows
_ia_tool_get_sales_timeseries = api.get_sales_timeseries
_ia_tool_detect_sales_anomalies = api.detect_sales_anomalies
_ia_tool_get_profit_by_period = api.get_profit_by_period
_ia_chat_scope_notice = api.scope_notice
_ia_tool_get_returns_data = api.get_returns_data
_ia_tool_get_returns_by_sku_period = api.get_returns_by_sku_period
_ia_vendas_db_consulta_sku_vendas_devolucoes = api.query_sku_sales_returns
_ia_vendas_db_consulta_sku = api.query_sku_sales
_ia_extrair_item_ids_ml = api.extract_ml_item_ids
_ia_lojas_ml_conectadas = api.connected_ml_stores
_ia_vendas_db_texto = api.sales_database_text
_ia_extrair_periodo_mensagem_vendas = api.extract_sales_period
_ia_extrair_periodos_comparacao = api.extract_comparison_periods
_ia_resolver_loja_mensagem_vendas = api.resolve_store
_ia_vendas_db_top_skus = api.get_top_skus
_ia_tool_get_sales_by_virtual_store_period = api.get_sales_by_virtual_store_period
_ia_tool_get_sales_by_sku_virtual_store = api.get_sales_by_sku_virtual_store
_ia_vendas_contexto_exato = api.get_exact_sales_context


PEER_EXPORTS = list(LEGACY_EXPORTS)
__all__ = PEER_EXPORTS + ["configure_ia_tools_vendas_runtime"]


configure_ia_tools_vendas_runtime()
