"""Compatibility facade for Perguntas/Pós-venda HTTP endpoints."""

from backend.modules.perguntas_pos_venda.endpoints.api import (
    ml_customer_reply_job_cancel,
    ml_customer_reply_job_status,
    ml_customer_reply_solicitacoes_list,
    ml_ia_treinamento_listar_skus,
    ml_ia_treinamento_sincronizacao_obter,
    ml_ia_treinamento_sincronizacao_solicitar,
    ml_ia_treinamento_obter,
    ml_ia_treinamento_salvar,
    ml_ia_treinamento_simular,
    ml_listar_perguntas,
    ml_perguntas_aprovacoes_aprovar,
    ml_perguntas_aprovacoes_listar,
    ml_perguntas_aprovacoes_rejeitar,
    ml_perguntas_automacao_poll,
    ml_perguntas_automacao_status,
    ml_perguntas_gerar_resposta_manual,
    ml_perguntas_listar_lojas,
    ml_perguntas_responder_manual,
    ml_perguntas_salvar_config_loja,
    ml_perguntas_salvar_config_lojas_lote,
    ml_pos_venda_automacao_poll,
    ml_pos_venda_detalhe_conversa,
    ml_pos_venda_gerar_resposta_conversa,
    ml_pos_venda_listar_conversas,
    ml_pos_venda_listar_mediacoes,
    ml_pos_venda_obter_anexo,
    ml_pos_venda_responder_conversa,
    ml_questions_v2_audit_question,
    ml_questions_v2_metrics,
    ml_questions_v2_pending_review,
    ml_questions_v2_process,
    ml_questions_v2_review_approve,
    ml_questions_v2_review_reject,
    ml_questions_v2_webhook,
)
from backend.modules.perguntas_pos_venda.endpoints.contracts import (
    PERGUNTAS_POS_VENDA_ENDPOINTS,
)
from backend.modules.perguntas_pos_venda.endpoints.runtime import configure_runtime


def configure_perguntas_pos_venda_endpoints_runtime(legacy_module) -> None:
    configure_runtime(legacy_module)


__all__ = [
    "PERGUNTAS_POS_VENDA_ENDPOINTS",
    "configure_perguntas_pos_venda_endpoints_runtime",
    "ml_perguntas_listar_lojas",
    "ml_perguntas_salvar_config_loja",
    "ml_perguntas_salvar_config_lojas_lote",
    "ml_perguntas_automacao_status",
    "ml_perguntas_automacao_poll",
    "ml_perguntas_aprovacoes_listar",
    "ml_perguntas_aprovacoes_aprovar",
    "ml_perguntas_aprovacoes_rejeitar",
    "ml_questions_v2_webhook",
    "ml_questions_v2_process",
    "ml_questions_v2_pending_review",
    "ml_questions_v2_review_approve",
    "ml_questions_v2_review_reject",
    "ml_questions_v2_audit_question",
    "ml_questions_v2_metrics",
    "ml_perguntas_gerar_resposta_manual",
    "ml_perguntas_responder_manual",
    "ml_ia_treinamento_obter",
    "ml_ia_treinamento_sincronizacao_obter",
    "ml_ia_treinamento_sincronizacao_solicitar",
    "ml_ia_treinamento_salvar",
    "ml_ia_treinamento_listar_skus",
    "ml_ia_treinamento_simular",
    "ml_pos_venda_listar_conversas",
    "ml_pos_venda_listar_mediacoes",
    "ml_pos_venda_detalhe_conversa",
    "ml_pos_venda_obter_anexo",
    "ml_pos_venda_gerar_resposta_conversa",
    "ml_pos_venda_responder_conversa",
    "ml_pos_venda_automacao_poll",
    "ml_customer_reply_job_status",
    "ml_customer_reply_job_cancel",
    "ml_customer_reply_solicitacoes_list",
    "ml_listar_perguntas",
]
