const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const canonical = fs.readFileSync(path.join(root, 'static', 'configuracoes.html'), 'utf8');
const mirror = fs.readFileSync(path.join(root, 'configuracoes.html'), 'utf8');
const ui = fs.readFileSync(path.join(root, 'static', 'configuracoes-whatsapp.js'), 'utf8');
const service = fs.readFileSync(path.join(root, 'backend', 'services', 'whatsapp_bridge.py'), 'utf8');
const codexConsole = fs.readFileSync(path.join(root, 'backend', 'services', 'codex_console.py'), 'utf8');
const setup = fs.readFileSync(path.join(root, 'scripts', 'setup-whatsapp-zero-cost.ps1'), 'utf8');
const wranglerExample = fs.readFileSync(path.join(root, 'cloudflare', 'whatsapp-gateway', 'wrangler.example.toml'), 'utf8');
const gateway = fs.readFileSync(path.join(root, 'cloudflare', 'whatsapp-gateway', 'src', 'index.ts'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'electron_app', 'installer-required-resources.json'), 'utf8'));

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

assert(canonical === mirror, 'configuracoes.html mirror diverged from static canonical');
assert(canonical.includes('data-tab="whatsapp"'), 'WhatsApp tab missing');
assert(canonical.includes('id="cardWhatsappJoao" class="card hidden"'), 'full-only WhatsApp card missing');
assert(canonical.includes('/configuracoes-whatsapp.js?v='), 'WhatsApp controller not loaded');
assert(canonical.includes('id="waPersonalPhones"'), 'multi-number list missing');
assert(canonical.includes('id="waPersonalPhoneCount"'), 'multi-number counter missing');
assert(canonical.includes('id="waTargetUser"'), 'per-user selector missing');
assert(canonical.includes('id="waAiModel"'), 'WhatsApp AI selector missing');
assert(canonical.includes('id="waCodexReasoning"'), 'Codex reasoning selector missing');
assert(canonical.includes('id="userWhatsappSettings"'), 'per-user WhatsApp phone settings are missing');
assert(canonical.includes('id="userWaNewPhoneName"'), 'direct phone name field is missing');
assert(canonical.includes('id="userWaNewPhoneNumber"'), 'direct phone number field is missing');
assert(canonical.includes('id="userWaSavePhone"'), 'direct phone save action is missing');
assert(canonical.includes('id="userWaWelcomeMessage"'), 'welcome message field is missing');
assert(canonical.includes('id="userWaSendWelcome"'), 'welcome send option is missing');
assert(canonical.includes('id="userWaSendWelcome" type="checkbox" checked'), 'welcome should be prepared by default');
assert(canonical.includes('Por regra da Meta'), 'the Meta service-window explanation is missing');
assert(canonical.includes('id="userWaAdhocPhone"'), 'ad hoc recipient field is missing');
assert(canonical.includes('id="userWaAdhocMessage"'), 'ad hoc message field is missing');
assert(canonical.includes('id="userWaSendAdhoc"'), 'ad hoc message send action is missing');
assert(canonical.includes('O nome e o número são salvos diretamente'), 'direct registration guidance is missing');
assert(canonical.includes('id="userWaPhones"'), 'user phone settings list is missing');
assert(ui.includes("permissions.full !== true"), 'UI is not restricted to full administrators');
assert(ui.includes('/api/admin/whatsapp/status'), 'status endpoint missing from UI');
assert(ui.includes('/api/admin/whatsapp/pairing-code'), 'pairing endpoint missing from UI');
assert(ui.includes('payload.binding_limit || 3'), 'three-number limit missing from UI');
assert(ui.includes('item.username === target.username && item.client_id === target.client_id'), 'numbers are not grouped by selected user');
assert(ui.includes('subject_id: item.subject_id, username: item.username, client_id: item.client_id'), 'individual number revoke missing');
assert(ui.includes('JSON.stringify({ revoke_all: true, ...target })'), 'per-user revoke-all option missing');
assert(ui.includes("request('/api/admin/users')"), 'JK user list is not loaded');
assert(ui.includes("request('/api/admin/whatsapp/phone-settings'"), 'per-phone notification settings endpoint is not used');
assert(ui.includes("request('/api/admin/whatsapp/phones'"), 'direct phone registration endpoint is not used');
assert(ui.includes('send_welcome_message: sendWelcomeMessage'), 'welcome message option is not sent by the UI');
assert(ui.includes("request('/api/admin/whatsapp/messages'"), 'ad hoc message endpoint is not used');
assert(ui.includes('Enviar sugestão de pergunta do Mercado Livre'), 'Mercado Livre question preference is missing');
assert(ui.includes('Enviar relatório semanal'), 'weekly report preference is missing');
assert(ui.includes('Enviar relatório mensal'), 'monthly report preference is missing');
assert(ui.includes('Como a IA deve se comportar com este usuário'), 'per-phone AI behavior field is missing');
assert(ui.includes('ai_behavior: behaviorInput.value.trim()'), 'per-phone AI behavior is not saved by the UI');
assert(ui.includes('window.jkWhatsappSelecionarUsuario'), 'selected JK user is not connected to phone settings');
assert(ui.includes("request('/api/ia/modelos')"), 'AI catalog is not loaded for WhatsApp');
assert(ui.includes("ai_model: String(aiModel.value || 'codex:gpt-5.5').trim()"), 'selected WhatsApp AI is not saved');
assert(ui.includes("codex_reasoning_effort: String(codexReasoning.value || 'xhigh').trim()"), 'Codex reasoning is not saved');
assert(ui.includes('/api/admin/whatsapp/whisper/download'), 'Whisper endpoint missing from UI');
assert(!ui.includes('payload.bridge_token_configured ? payload.bridge_token'), 'UI must never render the saved bridge token');
assert(service.includes('TRANSCRIPTION_TIMEOUT_SECONDS = 600'), 'transcription timeout changed');
assert(service.includes('POLL_SECONDS = 3'), 'bridge poll interval must be 3 seconds');
assert(service.includes('CLAIM_LIMIT = 5'), 'bridge claim limit changed');
assert(service.includes('TYPING_REFRESH_SECONDS = 20'), 'typing refresh must remain at 20 seconds');
assert(service.includes('TYPING_MAX_SECONDS = 10 * 60'), 'typing maximum duration must remain at 10 minutes');
assert(service.includes('/typing"'), 'local bridge typing endpoint missing');
assert(service.includes('pairing_pending'), 'pairing no longer auto-activates the local bridge');
assert(service.includes('WHATSAPP_AI_DEFAULT_MODEL = "codex:gpt-5.5"'), 'WhatsApp Codex default changed');
assert(service.includes('def _create_selected_ai_task('), 'selected WhatsApp AI is not routed');
assert(service.includes('class WhatsappPhoneSettingsRequest(BaseModel)'), 'phone settings request contract is missing');
assert(service.includes('class WhatsappPhoneRegistrationRequest(BaseModel)'), 'direct phone registration contract is missing');
assert(service.includes('def whatsapp_bridge_update_phone_settings('), 'phone settings endpoint is missing');
assert(service.includes('def _normalize_phone_ai_behavior('), 'per-phone AI behavior normalization is missing');
assert(service.includes('"phone_ai_behavior": phone_ai_behavior'), 'per-phone AI behavior is not attached to WhatsApp tasks');
assert(service.includes('Instrucoes administrativas especificas para atender este numero'), 'per-phone AI behavior is not applied to provider prompts');
assert(codexConsole.includes('Instrucao administrativa especifica para este numero de WhatsApp'), 'per-phone AI behavior is not applied as a Codex developer instruction');
assert(service.includes('def whatsapp_bridge_register_phone('), 'direct phone registration endpoint is missing');
assert(service.includes('"/bridge/welcome"'), 'welcome message is not sent by the local bridge');
assert(service.includes('def whatsapp_bridge_send_adhoc_message('), 'ad hoc message endpoint is missing');
assert(service.includes('"/bridge/messages/send"'), 'ad hoc message is not routed to the gateway');
assert(service.includes('phone_settings["send_ml_question_suggestions"]'), 'question suggestions do not honor the selected phone preference');
assert(service.includes('def _start_phone_notification_report_scan('), 'per-phone scheduled reports are missing');
const taskTransitionStart = service.indexOf('def _forward_task_transitions(');
const taskTransitionEnd = service.indexOf('\ndef ', taskTransitionStart + 4);
const taskTransitionForwarder = service.slice(taskTransitionStart, taskTransitionEnd);
assert(taskTransitionStart >= 0, 'task transition state mirror is missing');
assert(!taskTransitionForwarder.includes('_post_proactive('), 'sidebar tasks must never be forwarded to WhatsApp');
assert(wranglerExample.includes('database_id = "REPLACE_WITH_D1_DATABASE_ID"'), 'D1 placeholder changed');
assert(setup.includes('database_id = "REPLACE_WITH_D1_DATABASE_ID"'), 'setup no longer replaces the D1 placeholder');
assert(wranglerExample.includes('META_GRAPH_API_VERSION = "REPLACE_WITH_CURRENT_META_GRAPH_VERSION"'), 'Graph API placeholder changed');
assert(wranglerExample.includes('TYPING_PULSES_DAY_LIMIT = "10000"'), 'typing daily limit missing from Wrangler example');
assert(setup.includes('REPLACE_WITH_CURRENT_META_GRAPH_VERSION'), 'setup no longer replaces the Graph API placeholder');
assert(gateway.includes('const MAX_BINDINGS_PER_USER = 3'), 'gateway per-user binding limit changed');
assert(gateway.includes('binding_limit_reached'), 'gateway no longer blocks a fourth number');
assert(gateway.includes('async function registerBinding('), 'gateway direct binding registration is missing');
assert(gateway.includes('/bridge/bindings/register'), 'gateway direct binding route is missing');
assert(gateway.includes('async function welcomeMessage('), 'gateway welcome sender is missing');
assert(gateway.includes('/bridge/welcome'), 'gateway welcome route is missing');
assert(gateway.includes('async function adhocMessage('), 'gateway ad hoc sender is missing');
assert(gateway.includes('/bridge/messages/send'), 'gateway ad hoc message route is missing');
assert(gateway.includes("message_type='adhoc_text'"), 'ad hoc messages are not kept separate from automated replies');
assert(gateway.includes('Este número não possui permissão para acessar o Black Jhon'), 'unauthorized WhatsApp numbers do not receive an access notice');
assert(gateway.includes("event_type='unauthorized_access_notice'"), 'unauthorized access notices are not throttled');
assert(gateway.includes('["weekly_report", "monthly_report"].includes(eventType)'), 'scheduled report event types are not supported');
assert(gateway.includes('typing_indicator: { type: "text" }'), 'Meta typing payload missing');
assert(gateway.includes('TYPING_PULSES_DAY_LIMIT'), 'typing daily free-tier guard missing');
assert(gateway.includes('O erro tecnico ficou registrado no JK Sistema'), 'gateway exposes raw local errors to WhatsApp');
assert(manifest.requiredSourceFiles.includes('backend/services/whatsapp_bridge.py'), 'bridge missing from installer verification');
assert(manifest.requiredSourceFiles.includes('static/configuracoes-whatsapp.js'), 'WhatsApp UI missing from installer verification');
assert(manifest.forbiddenLocalAppFilters.includes('info/**'), 'local secrets/model directory must remain unpackaged');

console.log('WHATSAPP_CONFIG_REGRESSION_OK');
