"""Declarative read-only tool catalog."""

from __future__ import annotations

from typing import Any

from .settings import EXTERNAL_CACHE_SECONDS

CODEX_DATA_TOOLS: list[dict[str, Any]] = [
    {
        "id": "sales_returns_query",
        "module": "vendas_devolucoes",
        "description": "Consulta unificada de vendas e devolucoes por periodo, loja e SKU.",
        "intent_examples": ["vendas e devolucoes por loja", "maior devolucao", "vendas por sku no periodo"],
        "executor": "sales_returns_query",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["totais", "por_loja", "por_sku", "vendas", "devolucoes"],
        "fallbacks": ["sales_ranking", "returns_summary", "integrations_status"],
        "status": "consultando vendas e devolucoes",
    },
    {
        "id": "sales_ranking",
        "module": "vendas",
        "description": "Ranking de SKUs mais vendidos por periodo, com quantidade e valor.",
        "intent_examples": ["ranking dos ultimos 30 dias", "skus mais vendidos", "top produtos"],
        "executor": "_ia_tool_get_sales_by_period",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "nome", "qtd", "valor", "quantidade_total", "valor_total", "pedidos_total"],
        "fallbacks": ["integrations_status", "bling_sales_orders", "mercado_livre_listing"],
        "status": "consultando vendas locais",
    },
    {
        "id": "sales_summary",
        "module": "vendas",
        "description": "Resumo de quantidade vendida no periodo.",
        "intent_examples": ["quanto vendeu", "total vendido", "itens vendidos"],
        "executor": "_ia_tool_get_sales_quantity_by_period",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["quantidade_total", "quantidade_vendida_total"],
        "fallbacks": ["integrations_status"],
        "status": "resumindo vendas",
    },
    {
        "id": "returns_summary",
        "module": "devolucoes",
        "description": "Resumo e ranking de devolucoes por periodo.",
        "intent_examples": ["devolucoes do periodo", "produtos devolvidos", "taxa de devolucao"],
        "executor": "_ia_tool_get_returns_by_period",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["quantidade_devolvida_total", "valor_devolvido_total", "top_skus"],
        "fallbacks": ["integrations_status"],
        "status": "consultando devolucoes",
    },
    {
        "id": "return_rate",
        "module": "devolucoes",
        "description": "Taxa de devolucao por quantidade e por valor.",
        "intent_examples": ["taxa de devolucao", "percentual devolvido"],
        "executor": "_ia_tool_get_return_rate_by_period",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["taxa_devolucao_quantidade_percentual", "taxa_devolucao_valor_percentual"],
        "fallbacks": ["returns_summary"],
        "status": "calculando taxa de devolucao",
    },
    {
        "id": "profit_summary",
        "module": "margem",
        "description": "Lucro e margem estimados por periodo.",
        "intent_examples": ["lucro", "margem", "rentabilidade"],
        "executor": "_ia_tool_get_profit_by_period",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["lucro_estimado", "margem_percentual_estimada", "skus_considerados", "skus_com_custo"],
        "fallbacks": ["product_margin"],
        "status": "calculando margem",
    },
    {
        "id": "product_costs_and_margin",
        "module": "margem",
        "description": "Consulta custos/impostos do cadastro e calcula margem por SKU vendido usando a formula do Favoritos.",
        "intent_examples": ["margem real por sku", "custo dos produtos vendidos", "relatorio com lucro por produto"],
        "executor": "codex_assistant.product_costs_and_margin",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": [
            "sku",
            "produto",
            "quantidade_vendida",
            "valor_vendido",
            "custo_unitario",
            "custo_total",
            "imposto",
            "frete",
            "tarifa",
            "lucro_estimado",
            "margem_percentual",
            "status_margem",
        ],
        "fallbacks": ["sales_ranking", "product_margin", "mercado_livre_listing"],
        "status": "calculando custo e margem por SKU",
    },
    {
        "id": "stockout_forecast",
        "module": "estoque",
        "description": "Previsao de ruptura de estoque usando vendas recentes.",
        "intent_examples": ["risco de ruptura", "quando acaba", "estoque acabando"],
        "executor": "_ia_tool_get_stockout_forecast",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "saldo_total", "media_venda_dia", "dias_ate_ruptura", "risco_ruptura"],
        "fallbacks": ["stock_data", "sales_ranking"],
        "status": "consultando estoque",
    },
    {
        "id": "stale_stock",
        "module": "estoque",
        "description": "SKUs com saldo de loja e sem venda recente, com idade, custo cadastrado e capital estimado.",
        "intent_examples": ["estoque parado", "sem vender", "dias sem venda"],
        "executor": "_ia_tool_get_days_without_sale_top",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": [
            "sku",
            "produto",
            "saldo_loja",
            "saldo_full",
            "ultima_venda",
            "dias_sem_vender",
            "custo_unitario",
            "valor_custo_estoque_loja",
        ],
        "fallbacks": ["stock_data"],
        "status": "procurando estoque parado",
    },
    {
        "id": "avg_ticket",
        "module": "vendas",
        "description": "Ticket medio por periodo.",
        "intent_examples": ["ticket medio", "valor medio por pedido"],
        "executor": "_ia_tool_get_avg_ticket_by_period",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["ticket_medio", "pedidos_total", "valor_vendido_total"],
        "fallbacks": ["sales_ranking"],
        "status": "calculando ticket medio",
    },
    {
        "id": "period_comparison",
        "module": "vendas",
        "description": "Comparacao entre periodo atual e anterior.",
        "intent_examples": ["comparar periodo", "cresceu ou caiu", "mesmo periodo anterior"],
        "executor": "_ia_tool_get_period_comparison",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["variacao_quantidade_percentual", "variacao_faturamento_percentual", "variacao_pedidos_percentual"],
        "fallbacks": ["sales_ranking"],
        "status": "comparando periodos",
    },
    {
        "id": "sales_timeseries",
        "module": "vendas",
        "description": "Serie diaria de vendas e devolucoes.",
        "intent_examples": ["evolucao diaria", "curva de vendas", "serie temporal"],
        "executor": "_ia_tool_get_sales_timeseries",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["data", "quantidade_vendida", "valor_vendido", "quantidade_devolvida", "valor_devolvido"],
        "fallbacks": ["sales_ranking"],
        "status": "montando curva de vendas",
    },
    {
        "id": "sales_anomalies",
        "module": "vendas",
        "description": "Picos e quedas fora do padrao na curva de vendas.",
        "intent_examples": ["anomalias", "queda de venda", "pico de venda"],
        "executor": "_ia_tool_detect_sales_anomalies",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["alertas", "media_valor_diario", "desvio_padrao_valor_diario"],
        "fallbacks": ["sales_timeseries"],
        "status": "detectando anomalias",
    },
    {
        "id": "integrations_status",
        "module": "integracoes",
        "description": "Status read-only de conexoes Mercado Livre e Bling por loja.",
        "intent_examples": ["status integracoes", "contas conectadas", "token vencido"],
        "executor": "_ia_tool_get_integrations_status",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["loja", "mercado_livre_conectado", "bling_conectado"],
        "fallbacks": [],
        "status": "validando integracoes",
    },
    {
        "id": "mercado_livre_listing",
        "module": "anuncios",
        "description": "Consulta read-only de anuncios Mercado Livre conectados.",
        "intent_examples": ["anuncios mercado livre", "saude do anuncio", "itens ativos"],
        "executor": "_ia_tool_get_mercado_livre_listing",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": [
            "id", "title", "status", "seller_sku", "price", "available_quantity", "sold_quantity",
            "health", "permalink", "description", "pictures", "picture_urls",
        ],
        "fallbacks": ["integrations_status"],
        "status": "consultando Mercado Livre read-only",
    },
    {
        "id": "mercado_livre_resource_query",
        "module": "mercado_livre",
        "description": "Catalogo oficial versionado e executor fechado de endpoints de consulta do Mercado Livre. Aceita resource_id; nunca URL livre.",
        "intent_examples": [
            "catalogo de endpoints mercado livre",
            "consultar recurso oficial do mercado livre",
            "buscar estoque de user product ou desempenho do anuncio",
        ],
        "executor": "mercado_livre_query_service.execute_mercado_livre_query",
        "external": True,
        "read_only": True,
        "sensitive": True,
        "cache_ttl_seconds": 0,
        "output_fields": ["catalog_version", "resource", "data", "rows", "records", "sources"],
        "fallbacks": [],
        "zero_is_authoritative": True,
        "source_role": "primary_api",
        "aggregation_policy": "separate_sources_no_sum",
        "status": "consultando recurso oficial do Mercado Livre",
    },
    {
        "id": "mercado_livre_visits",
        "module": "anuncios",
        "description": "Visitas diarias de um anuncio MLB exato, com ownership confirmado na loja escolhida.",
        "intent_examples": ["visitas do MLB", "visualizacoes do anuncio", "acessos nos ultimos 30 dias"],
        "executor": "_ia_tool_get_mercado_livre_visits",
        "external": True,
        "read_only": True,
        "cache_ttl_seconds": 120,
        "output_fields": ["item_id", "date_from", "date_to", "total_visits", "average", "record", "results"],
        "fallbacks": [],
        "zero_is_authoritative": True,
        "status": "consultando visitas do anuncio no Mercado Livre",
    },
    {
        "id": "mercado_livre_promotions",
        "module": "anuncios",
        "description": "Campanhas e promocoes read-only da conta Mercado Livre exata.",
        "intent_examples": ["campanhas do mercado livre", "promocoes ativas", "ofertas da conta"],
        "executor": "_ia_tool_get_mercado_livre_promotions",
        "external": True,
        "read_only": True,
        "cache_ttl_seconds": 120,
        "output_fields": ["id", "name", "type", "status", "start_date", "finish_date", "benefits", "counts"],
        "fallbacks": [],
        "zero_is_authoritative": True,
        "status": "consultando promocoes do Mercado Livre",
    },
    {
        "id": "mercado_livre_post_sale_detail",
        "module": "perguntas_pos_venda",
        "description": "Conversa read-only de pos-venda por pack exato, com PII e URLs privadas removidas.",
        "intent_examples": ["mensagens do pack", "detalhe da conversa pos venda", "anexos da conversa"],
        "executor": "codex_readonly_sources.mercado_livre_post_sale_detail",
        "external": True,
        "read_only": True,
        "sensitive": True,
        "cache_ttl_seconds": 0,
        "output_fields": ["pack_id", "order_id", "status", "items", "messages", "messages_returned"],
        "fallbacks": [],
        "zero_is_authoritative": True,
        "status": "consultando conversa de pos-venda Mercado Livre",
    },
    {
        "id": "mercado_livre_orders",
        "module": "vendas_mercado_livre",
        "description": "Consulta read-only de pedidos e vendas pela API do Mercado Livre.",
        "intent_examples": ["pedidos mercado livre", "vendas via api mercado livre", "pedidos pagos por sku"],
        "executor": "_ia_tool_get_mercado_livre_orders",
        "external": True,
        "read_only": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": [
            "order_id", "pack_id", "status", "date_created", "date_closed",
            "items", "gross_amount", "paid_amount", "refund_amount", "net_amount",
            "buyer_name", "buyer_nickname", "shipment", "fulfillment", "claims",
            "returns", "conversations",
        ],
        "fallbacks": [],
        "companion_tools": ["bling_sales_orders"],
        "zero_is_authoritative": True,
        "status": "consultando pedidos Mercado Livre read-only",
    },
    {
        "id": "mercado_livre_returns",
        "module": "vendas_mercado_livre",
        "description": "Consulta devolucoes diretamente na API de claims/returns do Mercado Livre, ordenadas pela atualizacao mais recente.",
        "intent_examples": ["ultima devolucao da loja", "devolucoes mercado livre", "retorno mais recente pela api"],
        "executor": "_ia_tool_get_mercado_livre_returns",
        "external": True,
        "read_only": True,
        "cache_ttl_seconds": 15,
        "output_fields": ["claim_id", "order_id", "last_updated", "status", "reason_id", "order", "return_detail"],
        "fallbacks": [],
        "zero_is_authoritative": True,
        "status": "consultando devolucoes Mercado Livre read-only",
    },
    {
        "id": "mercado_livre_full_stock",
        "module": "mercado_full",
        "description": "Estoque Full atual consultado exclusivamente na API de inventario do Mercado Livre.",
        "intent_examples": ["estoque full", "saldo fulfillment", "somar estoque full por sku"],
        "executor": "full_mercadolivre.listar_anuncios_full_mercadolivre_payload",
        "external": True,
        "read_only": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "inventory_id", "full_available_quantity", "full_not_available_quantity", "full_total_quantity"],
        "fallbacks": [],
        "zero_is_authoritative": True,
        "source_role": "primary_api",
        "aggregation_policy": "full_mercado_livre_only",
        "status": "consultando estoque Full no Mercado Livre",
    },
    {
        "id": "bling_product",
        "module": "bling",
        "description": "Consulta read-only de produto no Bling quando houver SKU/produto.",
        "intent_examples": ["produto no bling", "id bling", "dados bling"],
        "executor": "_ia_tool_get_bling_product",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "id", "nome", "preco", "estoque"],
        "fallbacks": ["integrations_status", "product_data"],
        "status": "consultando Bling read-only",
    },
    {
        "id": "bling_status",
        "module": "bling",
        "description": "Status read-only das contas Bling, canais e depositos conectados.",
        "intent_examples": ["status bling", "contas bling conectadas", "token bling"],
        "executor": "codex_bling_tools.bling_status",
        "external": True,
        "cache_ttl_seconds": 30 * 60,
        "output_fields": ["loja", "bling_conectado", "canais_venda", "depositos"],
        "fallbacks": ["integrations_status"],
        "status": "validando Bling read-only",
    },
    {
        "id": "bling_products",
        "module": "bling",
        "description": "Busca read-only de produtos Bling por SKU, nome, ID, codigo ou GTIN.",
        "intent_examples": ["buscar produto na bling", "dados do sku no bling", "produto por ean"],
        "executor": "codex_bling_tools.bling_products",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["id", "sku", "nome", "preco", "preco_custo", "ncm", "cest"],
        "fallbacks": ["product_data", "integrations_status"],
        "status": "consultando produtos Bling",
    },
    {
        "id": "bling_fiscal_product",
        "module": "bling",
        "description": "Dados fiscais read-only do produto no Bling, incluindo NCM, CEST, origem e unidade.",
        "intent_examples": ["ncm do sku na bling", "cest produto bling", "dados fiscais do produto"],
        "executor": "codex_bling_tools.bling_fiscal_product",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "ncm", "cest", "origem", "unidade", "preco_custo"],
        "fallbacks": ["bling_products", "product_registry"],
        "status": "consultando fiscal de produto Bling",
    },
    {
        "id": "bling_stock_balances",
        "module": "bling",
        "description": "Saldo de estoque read-only da Bling geral e por deposito.",
        "intent_examples": ["saldo em estoque na bling", "estoque do sku no bling", "saldo por deposito"],
        "executor": "codex_bling_tools.bling_stock_balances",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "produto", "saldo_total", "depositos"],
        "fallbacks": ["bling_products", "stock_data"],
        "status": "consultando saldo Bling",
    },
    {
        "id": "bling_positive_stock_sku_count",
        "module": "bling",
        "description": "Conta, com paginacao completa, os SKUs distintos com saldo positivo na loja Bling selecionada.",
        "intent_examples": ["quantos SKUs estao com estoque", "numero de produtos com saldo positivo", "total de SKUs com estoque na loja"],
        "executor": "codex_bling_tools.bling_positive_stock_sku_count",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["loja", "positive_sku_count", "store_available", "coverage_complete", "catalog_products_scanned"],
        "fallbacks": [],
        "zero_is_authoritative": True,
        "status": "contando SKUs com estoque na Bling",
    },
    {
        "id": "bling_deposits",
        "module": "bling",
        "description": "Lista read-only de depositos Bling e classificacao loja/full.",
        "intent_examples": ["depositos bling", "estoque full bling", "deposito padrao"],
        "executor": "codex_bling_tools.bling_deposits",
        "external": True,
        "cache_ttl_seconds": 30 * 60,
        "output_fields": ["id", "descricao", "situacao", "tipo_detectado"],
        "fallbacks": ["bling_status"],
        "status": "consultando depositos Bling",
    },
    {
        "id": "bling_sales_orders",
        "module": "bling",
        "description": "Pedidos de venda Bling por periodo, com ranking por SKU quando detalhes estiverem disponiveis.",
        "intent_examples": ["vendas na bling ultimos 30 dias", "pedidos bling", "ranking skus bling"],
        "executor": "codex_bling_tools.bling_sales_orders",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["pedidos", "top_skus", "sku", "quantidade_vendida", "valor_total"],
        "fallbacks": ["sales_ranking", "integrations_status"],
        "status": "consultando pedidos Bling",
    },
    {
        "id": "bling_sales_order_detail",
        "module": "bling",
        "description": "Detalhe read-only de um pedido de venda Bling por ID.",
        "intent_examples": ["detalhe pedido bling 123", "itens do pedido bling"],
        "executor": "codex_bling_tools.bling_sales_order_detail",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["id", "numero", "situacao", "itens"],
        "fallbacks": ["bling_sales_orders"],
        "status": "consultando pedido Bling",
    },
    {
        "id": "bling_fiscal_nfe",
        "module": "bling",
        "description": "NF-e Bling read-only por periodo, tipo, numero, situacao ou chave.",
        "intent_examples": ["notas fiscais bling", "nfe ultimos 30 dias", "nota de saida bling"],
        "executor": "codex_bling_tools.bling_fiscal_nfe",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["id", "numero", "serie", "situacao", "tipo", "valor", "chave_acesso"],
        "fallbacks": ["bling_operation_natures", "integrations_status"],
        "status": "consultando NF-e Bling",
    },
    {
        "id": "bling_fiscal_nfe_detail",
        "module": "bling",
        "description": "Detalhe read-only de NF-e Bling por ID ou chave de acesso.",
        "intent_examples": ["detalhe nfe bling", "nota fiscal chave"],
        "executor": "codex_bling_tools.bling_fiscal_nfe_detail",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["id", "numero", "itens", "tributacao"],
        "fallbacks": ["bling_fiscal_nfe"],
        "status": "consultando detalhe NF-e Bling",
    },
    {
        "id": "bling_operation_natures",
        "module": "bling",
        "description": "Naturezas de operacao Bling read-only.",
        "intent_examples": ["naturezas bling", "natureza de operacao", "tributacao bling"],
        "executor": "codex_bling_tools.bling_operation_natures",
        "external": True,
        "cache_ttl_seconds": 30 * 60,
        "output_fields": ["id", "descricao"],
        "fallbacks": ["integrations_status"],
        "status": "consultando naturezas Bling",
    },
    {
        "id": "bling_lots",
        "module": "bling",
        "description": "Lotes de produtos Bling read-only por SKU/produto.",
        "intent_examples": ["lotes do sku", "validade produto bling", "controle de lote"],
        "executor": "codex_bling_tools.bling_lots",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["id", "id_produto", "sku", "produto", "validade", "saldo"],
        "fallbacks": ["bling_products"],
        "status": "consultando lotes Bling",
    },
    {
        "id": "bling_lot_movements",
        "module": "bling",
        "description": "Lancamentos de lote Bling read-only por ID de lote ou SKU.",
        "intent_examples": ["movimentos do lote", "lancamentos lote bling", "entradas e saidas lote"],
        "executor": "codex_bling_tools.bling_lot_movements",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["id_lote", "sku", "produto", "quantidade", "tipo", "data"],
        "fallbacks": ["bling_lots"],
        "status": "consultando lancamentos Bling",
    },
    {
        "id": "bling_finance_summary",
        "module": "bling",
        "description": "Resumo read-only financeiro Bling: contas a receber, pagar e caixas.",
        "intent_examples": ["financeiro bling", "contas a receber bling", "contas a pagar"],
        "executor": "codex_bling_tools.bling_finance_summary",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["tipo", "quantidade", "valor_total", "amostra"],
        "fallbacks": ["bling_resource_query"],
        "status": "consultando financeiro Bling",
    },
    {
        "id": "bling_resource_query",
        "module": "bling",
        "description": "Fallback generico seguro para rotas Bling read-only liberadas por allowlist.",
        "intent_examples": ["consultar recurso bling", "qualquer informacao da bling", "rota bling"],
        "executor": "codex_bling_tools.bling_resource_query",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["rows", "resources", "sources"],
        "fallbacks": ["bling_status"],
        "status": "consultando recurso Bling read-only",
    },
    {
        "id": "product_data",
        "module": "cadastro",
        "description": "Cadastro/estoque local de produtos por SKU ou termo.",
        "intent_examples": ["dados do produto", "buscar sku", "cadastro produto"],
        "executor": "_ia_tool_get_product_data",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "nome", "saldo_loja", "saldo_full", "preco", "custo", "imposto"],
        "fallbacks": ["bling_product", "mercado_livre_listing"],
        "status": "consultando cadastro local",
    },
    {
        "id": "product_registry",
        "module": "cadastro",
        "description": "Informacoes completas do cadastro de produtos.",
        "intent_examples": ["ncm", "cest", "descricao", "dados fiscais do produto"],
        "executor": "_ia_tool_get_product_registry_info",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "nome", "ncm", "cest", "descricao"],
        "fallbacks": ["product_data"],
        "status": "consultando cadastro detalhado",
    },
    {
        "id": "stock_data",
        "module": "estoque",
        "description": "Saldo local de estoque por SKU ou produto.",
        "intent_examples": ["saldo do sku", "estoque do produto"],
        "executor": "_ia_tool_get_stock_data",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "saldo_loja_total", "saldo_full_total", "saldo_total"],
        "fallbacks": ["product_data"],
        "status": "consultando saldo local",
    },
    {
        "id": "product_margin",
        "module": "impostos",
        "description": "Margem/custo/imposto de um produto especifico.",
        "intent_examples": ["margem do sku", "custo do produto", "imposto do produto"],
        "executor": "_ia_tool_get_product_margin",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "preco", "custo", "imposto", "margem"],
        "fallbacks": ["product_data"],
        "status": "consultando margem do produto",
    },
    {
        "id": "product_image",
        "module": "cadastro",
        "description": "Imagem local/ML do produto quando houver SKU ou termo.",
        "intent_examples": ["imagem do produto", "foto do sku"],
        "executor": "_ia_tool_get_product_image",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sku", "imagem_url", "imagem_markdown"],
        "fallbacks": ["product_data", "mercado_livre_listing"],
        "status": "buscando imagem do produto",
    },
    {
        "id": "source_discovery",
        "module": "sistema",
        "description": "Descobre fontes read-only disponiveis no info do cliente: bancos, CSVs, caches, logs e JSONs.",
        "intent_examples": ["quais fontes voce consegue consultar", "liste bases locais", "fontes de dados disponiveis"],
        "executor": "codex_readonly_sources.discover_data_sources",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["sources", "total_sources", "schema"],
        "fallbacks": ["program_functions_catalog"],
        "status": "descobrindo fontes read-only",
    },
    {
        "id": "local_database_query",
        "module": "dados_locais",
        "description": "Consulta segura em bancos SQLite locais, somente SELECT, dentro de info/<client_id>.",
        "intent_examples": ["busque no banco local", "procure nos sqlite", "consulte vendas_historico"],
        "executor": "codex_readonly_sources.local_database_query",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["records", "sources", "filters"],
        "fallbacks": ["local_csv_query", "sync_logs_query"],
        "status": "consultando bancos locais",
    },
    {
        "id": "local_csv_query",
        "module": "dados_locais",
        "description": "Consulta read-only em CSVs locais de cadastro, custos, produtos, importacoes e mapas.",
        "intent_examples": ["busque nos csv", "cadastro_custos_lojas", "cadastro_produtos"],
        "executor": "codex_readonly_sources.local_csv_query",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["records", "sources", "filters"],
        "fallbacks": ["local_database_query", "local_cache_query"],
        "status": "consultando CSVs locais",
    },
    {
        "id": "local_cache_query",
        "module": "dados_locais",
        "description": "Consulta caches/JSONs locais com segredos redigidos.",
        "intent_examples": ["busque no cache", "cache mercado livre", "historico favorito", "json local"],
        "executor": "codex_readonly_sources.local_cache_query",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["records", "sources", "sensitive_fields_redacted"],
        "fallbacks": ["source_discovery"],
        "status": "consultando caches locais",
    },
    {
        "id": "sync_logs_query",
        "module": "integracoes",
        "description": "Consulta logs, estados e erros de sincronizacao sem executar sync.",
        "intent_examples": ["por que nao aparecem vendas", "erro de sincronizacao", "status do sync", "logs de sync"],
        "executor": "codex_readonly_sources.sync_logs_query",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["records", "sources", "warnings"],
        "fallbacks": ["integrations_status", "source_discovery"],
        "status": "consultando logs de sincronizacao",
    },
    {
        "id": "mercado_livre_readonly",
        "module": "mercado_livre",
        "description": "Consulta Mercado Livre em modo read-only: anuncios, itens e contexto local de perguntas.",
        "intent_examples": ["anuncios mercado livre", "pergunta aberta no ML", "dados do item Mercado Livre"],
        "executor": "codex_readonly_sources.mercado_livre_readonly",
        "external": True,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["records", "sources", "warnings"],
        "fallbacks": ["mercado_livre_listing", "questions_post_sale_query", "local_cache_query"],
        "status": "consultando Mercado Livre read-only",
    },
    {
        "id": "questions_post_sale_query",
        "module": "perguntas_pos_venda",
        "description": "Consulta a fila atual do Mercado Livre por loja e retorna perguntas, anuncio, produto e historico do comprador para auxiliar a resposta.",
        "intent_examples": ["perguntas abertas", "pos venda pendente", "perguntas respondidas", "aprovacoes ML"],
        "executor": "codex_readonly_sources.questions_post_sale_query",
        "external": True,
        "cache_ttl_seconds": 15,
        "output_fields": ["records", "questions_by_store", "coverage_complete", "sources", "warnings"],
        "fallbacks": [],
        "status": "consultando perguntas e pos-venda",
    },
    {
        "id": "fiscal_local_query",
        "module": "fiscal",
        "description": "Consulta fiscal local: NCM, CEST, impostos, aliquotas, regras e cadastro fiscal.",
        "intent_examples": ["dados fiscais do sku", "ncm cest", "regras fiscais", "imposto local"],
        "executor": "codex_readonly_sources.fiscal_local_query",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["records", "sources", "warnings"],
        "fallbacks": ["bling_fiscal_product", "bling_fiscal_nfe"],
        "status": "consultando fiscal local",
    },
    {
        "id": "operational_memory_query",
        "module": "memoria_operacional",
        "description": "Consulta preferencias, lojas, SKUs, decisoes, relatorios e contexto operacional salvo do Black Jhon.",
        "intent_examples": ["o que voce lembra", "preferencias da loja", "skus frequentes", "relatorios anteriores"],
        "executor": "codex_operational_memory.query_memory",
        "external": False,
        "cache_ttl_seconds": 0,
        "output_fields": ["category", "content", "metadata", "source", "importance"],
        "fallbacks": [],
        "status": "consultando memoria operacional",
    },
    {
        "id": "context_hub_search",
        "module": "sistema",
        "description": "Busca read-only na geracao ativa e validada do Context Hub tecnico do JK Sistema.",
        "intent_examples": ["como funciona esta tela", "qual rota implementa isso", "arquitetura do modulo", "contexto tecnico do SKU"],
        "executor": "context_hub.search_context",
        "external": False,
        "cache_ttl_seconds": 0,
        "output_fields": ["doc_id", "chunk_id", "snippet", "score", "reference", "truth_class", "source_version", "source_hash", "generation_id"],
        "fallbacks": [],
        "status": "consultando Context Hub",
    },
    {
        "id": "program_functions_catalog",
        "module": "sistema",
        "description": "Catalogo normalizado de capacidades, rotas, telas, servicos e acoes aprovaveis do JK Sistema.",
        "intent_examples": ["liste todas as funcoes", "o que o programa faz", "o que voce consegue fazer", "rotas do sistema", "modulos disponiveis"],
        "executor": "codex_capabilities.list_capabilities",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["capabilities", "modules", "totals"],
        "fallbacks": ["operational_dispatcher"],
        "status": "consultando catalogo do programa",
    },
    {
        "id": "capability_resolve",
        "module": "sistema",
        "description": "Resolve a intencao do usuario para uma capacidade do JK Sistema antes de dizer que nao consegue.",
        "intent_examples": ["como faco isso no sistema", "voce consegue responder pergunta ML", "qual ferramenta usa para saldo Bling"],
        "executor": "codex_capabilities.resolve_capability",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["capability", "candidates", "missing_params"],
        "fallbacks": ["program_functions_catalog", "program_action_match"],
        "status": "resolvendo capacidade",
    },
    {
        "id": "program_action_match",
        "module": "sistema",
        "description": "Identifica se um pedido pode virar acao operacional aprovada, sem executar nada.",
        "intent_examples": ["voce consegue sincronizar vendas", "pode atualizar estoque", "qual acao executa isso", "faca isso no programa"],
        "executor": "codex_actions.match_action_dry_run",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["matched", "action", "params", "missing_params", "requires_confirmation"],
        "fallbacks": ["program_functions_catalog"],
        "status": "avaliando acao disponivel",
    },
    {
        "id": "operational_dispatcher",
        "module": "full_favoritos_perguntas_impostos",
        "description": "Dispatcher read-only legado para Full, Favoritos, perguntas/pos-venda, impostos e consultas especificas ainda nao mapeadas diretamente.",
        "intent_examples": ["full", "favoritos", "perguntas", "pos-venda", "impostos"],
        "executor": "_ia_chat_executar_funcoes",
        "external": False,
        "cache_ttl_seconds": EXTERNAL_CACHE_SECONDS,
        "output_fields": ["tool_results"],
        "fallbacks": ["integrations_status"],
        "status": "consultando modulo operacional",
    },
]

# O registro historico nasceu exclusivamente com leitores e varias entradas
# antigas nao declaravam o campo. Materialize o contrato no proprio registro
# para que catalogo e executor possam falhar fechados sem quebrar compatibilidade.
for _tool_contract in CODEX_DATA_TOOLS:
    _tool_contract.setdefault("read_only", True)

# Consultas direcionadas a uma API devem preservar o zero retornado por essa
# fonte. Um resultado vazio do provedor nao pode virar silenciosamente dados de
# banco local ou de outra integracao.
for _api_tool_id in {"mercado_livre_listing", "mercado_livre_resource_query", "mercado_livre_visits", "mercado_livre_promotions", "mercado_livre_post_sale_detail", "mercado_livre_orders", "mercado_livre_returns", "mercado_livre_full_stock", "bling_sales_orders", "questions_post_sale_query"}:
    for _tool_contract in CODEX_DATA_TOOLS:
        if str(_tool_contract.get("id") or "") == _api_tool_id:
            _tool_contract["zero_is_authoritative"] = True
            _tool_contract["fallbacks"] = []
            _tool_contract["source_role"] = "primary_api"
            _tool_contract["aggregation_policy"] = "separate_sources_no_sum"
            if _api_tool_id == "bling_sales_orders":
                _tool_contract["companion_tools"] = ["mercado_livre_orders"]
            elif _api_tool_id == "mercado_livre_orders":
                _tool_contract["companion_tools"] = ["bling_sales_orders"]
            break
