"""Configuration constants for the modular Codex Assistant."""

from __future__ import annotations

import os

PROACTIVE_INTERVAL_SECONDS = 30 * 60
EXTERNAL_CACHE_SECONDS = 120
API_QUERY_TIMEOUT_SECONDS = 60
DAILY_ANALYSIS_ENABLED = False
REPORT_FORMATS = {"html", "xlsx", "pdf"}
DEFAULT_RANKING_LIMIT = 50
BLING_REPORT_LIMIT = 200
CODEX_DATA_TOOLS_VERSION = "20260731-data-tools-v23-evidence-envelope"
CODEX_DATA_CONTEXT_CHAR_LIMIT = int(os.getenv("JK_CODEX_DATA_CONTEXT_CHAR_LIMIT") or "64000")
CODEX_DATA_PREVIEW_CHAR_LIMIT = int(os.getenv("JK_CODEX_DATA_PREVIEW_CHAR_LIMIT") or "24000")
CODEX_SALES_RETURNS_CONTEXT_CHAR_LIMIT = int(os.getenv("JK_CODEX_SALES_RETURNS_CONTEXT_CHAR_LIMIT") or "64000")
CODEX_AGENT_NORMAL_ROW_LIMIT = int(os.getenv("JK_CODEX_AGENT_NORMAL_ROW_LIMIT") or "50")
CODEX_AGENT_REPORT_ROW_LIMIT = int(os.getenv("JK_CODEX_AGENT_REPORT_ROW_LIMIT") or "200")
CODEX_AGENT_TOP_ROWS_LIMIT = int(os.getenv("JK_CODEX_AGENT_TOP_ROWS_LIMIT") or "16")
CODEX_AGENT_TEXT_VALUE_LIMIT = int(os.getenv("JK_CODEX_AGENT_TEXT_VALUE_LIMIT") or "900")
