"""Stable facade for bounded public research and reusable product evidence."""

from __future__ import annotations

import time

from .deep_research_analysis import (
    _brand_tokens,
    _categorical_claims,
    _decisive_title_identity_tokens,
    _host_matches_official_brand,
    _host_matches_roots,
    _identity_terms,
    _item_attribute,
    _measurement_claims,
    _product_oem_codes,
    _selected_variation_tokens,
    classify_research_source,
    document_matches_product,
    expected_fields_for_research,
    expected_fields_from_question,
    extract_guarded_commercial_claims,
    extract_technical_claims,
)
from .deep_research_contracts import (
    PRODUCT_EVIDENCE_POLICY,
    PUBLIC_RESEARCH_MAX_DOMAINS,
    PUBLIC_RESEARCH_MAX_PAGES,
    PUBLIC_RESEARCH_MAX_PAGES_PER_DOMAIN,
    PUBLIC_RESEARCH_MAX_QUERIES,
    PUBLIC_RESEARCH_MAX_READERS,
    PUBLIC_RESEARCH_MAX_SECONDS,
    PUBLIC_RESEARCH_POLICY,
    ResearchDocumentV1,
    ResearchSessionV1,
    TechnicalClaimV1,
    _BLOG_PATH_PARTS,
    _COMMON_TWO_LABEL_PUBLIC_SUFFIXES,
    _CPF_CNPJ_RE,
    _CURATED_TECHNICAL_DISTRIBUTOR_DOMAINS,
    _CURATED_TECHNICAL_INDEPENDENT_DOMAINS,
    _DISTRIBUTOR_HOST_PARTS,
    _EMAIL_RE,
    _FORUM_HOST_PARTS,
    _IDENTITY_STOPWORDS,
    _MARKETPLACE_HOSTS,
    _MISSING_FACT_VALUES,
    _OEM_LABEL_METADATA,
    _SESSIONS,
    _SESSION_LOCK,
    _SESSION_TTL_SECONDS,
    _VIN_ANYWHERE_RE,
    _VIN_GROUPED_ANYWHERE_RE,
    _VIN_LABELLED_TAIL_RE,
    _domain,
    _label_metadata_code,
    _missing_fact_value,
    _plain,
    _registrable_domain,
    _safe_page_text,
    _safe_public_query,
    _safe_text,
    canonical_research_url,
    research_session,
)
from .deep_research_documents import (
    _field_is_covered,
    _identity_complete,
    apparent_coverage_complete,
    compact_verified_evidence,
    evidence_identity,
    listing_document,
    load_verified_product_evidence,
    make_research_document,
    persist_research_documents,
)
from .deep_research_fingerprints import (
    _deduplicate_research_documents,
    _technical_content_equivalent,
    _technical_content_hash,
    _technical_copy_fingerprint,
)
