import { createPairingCode, registerBinding, revokeBinding, updatePrimaryBinding } from "./bindings";
import { adhocMessage, welcomeMessage } from "./delivery";
import { bridgeMedia } from "./inbound-media";
import { claimMessages, messageProgress, messageResult, messageTyping } from "./messages";
import { businessProfile, finalizeMetaWebhook, metaCallingStatus, prepareMetaCallingSip, updateProfilePhoto } from "./meta-admin";
import { messageImage, proactiveImage } from "./outbound-media";
import { interactiveApproval, proactive } from "./proactive";
import { bridgeAuthorized, Env, json } from "./shared";
import { bridgeHeartbeat, bridgeStatus } from "./status";
import { syncTemplates } from "./templates";
import { claimVoiceCalls, updateVoiceCallState, voiceBridgeStatus, voiceHeartbeat, voicePhoneSettings } from "./voice";

export async function bridgeRoute(request: Request, env: Env): Promise<Response> {
  if (!bridgeAuthorized(request, env)) return json({ success: false, error: "unauthorized" }, 401);
  const url = new URL(request.url);
  if (request.method === "GET" && url.pathname === "/bridge/status") return bridgeStatus(request, env);
  if (request.method === "GET" && url.pathname === "/bridge/meta/profile") return businessProfile(env);
  if (request.method === "GET" && url.pathname === "/bridge/meta/calling/status") return metaCallingStatus(env);
  if (request.method === "POST" && url.pathname === "/bridge/meta/calling/prepare") return prepareMetaCallingSip(env);
  if (request.method === "POST" && url.pathname === "/bridge/pairing-codes") return createPairingCode(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/bindings/register") return registerBinding(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/bindings/primary") return updatePrimaryBinding(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/welcome") return welcomeMessage(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/messages/send") return adhocMessage(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/claim") return claimMessages(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/heartbeat") return bridgeHeartbeat(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/proactive") return proactive(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/proactive/image") return proactiveImage(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/proactive/document") return proactiveImage(request, env, "document");
  if (request.method === "POST" && url.pathname === "/bridge/interactive") return interactiveApproval(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/templates/sync") return syncTemplates(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/meta/finalize") return finalizeMetaWebhook(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/meta/profile/photo") return updateProfilePhoto(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/bindings/revoke") return revokeBinding(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/voice/heartbeat") return voiceHeartbeat(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/voice/phones/settings") return voicePhoneSettings(request, env);
  if (request.method === "POST" && url.pathname === "/bridge/voice/calls/claim") return claimVoiceCalls(request, env);
  if (request.method === "GET" && url.pathname === "/bridge/voice/status") return voiceBridgeStatus(env);
  const voiceStateMatch = url.pathname.match(/^\/bridge\/voice\/calls\/([^/]+)\/state$/);
  if (request.method === "POST" && voiceStateMatch) return updateVoiceCallState(request, env, decodeURIComponent(voiceStateMatch[1]));
  const mediaMatch = url.pathname.match(/^\/bridge\/media\/([^/]+)$/);
  if (request.method === "GET" && mediaMatch) return bridgeMedia(request, env, decodeURIComponent(mediaMatch[1]));
  const imageMatch = url.pathname.match(/^\/bridge\/messages\/([^/]+)\/image$/);
  if (request.method === "POST" && imageMatch) return messageImage(request, env, decodeURIComponent(imageMatch[1]));
  const documentMatch = url.pathname.match(/^\/bridge\/messages\/([^/]+)\/document$/);
  if (request.method === "POST" && documentMatch) return messageImage(request, env, decodeURIComponent(documentMatch[1]), "document");
  const typingMatch = url.pathname.match(/^\/bridge\/messages\/([^/]+)\/typing$/);
  if (request.method === "POST" && typingMatch) return messageTyping(request, env, decodeURIComponent(typingMatch[1]));
  const progressMatch = url.pathname.match(/^\/bridge\/messages\/([^/]+)\/progress$/);
  if (request.method === "POST" && progressMatch) return messageProgress(request, env, decodeURIComponent(progressMatch[1]));
  const resultMatch = url.pathname.match(/^\/bridge\/messages\/([^/]+)\/result$/);
  if (request.method === "POST" && resultMatch) return messageResult(request, env, decodeURIComponent(resultMatch[1]));
  return json({ success: false, error: "not_found" }, 404);
}
